language: node_js
node_js:
  - 6.13.4
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
cache:
  directories:
  - node_modules
  # folder with Cypress binary
  - ~/.cache
before_script:
  - npm cache clean --force
  - rm -rf node_modules package-lock.json
  - npm install
script:
  - npm run test:ci
  - npm run build